# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test',
  syntax='proto3',
  serialized_options=b'Z\"go-grpc-test/test-proto;test_proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\x04test\"9\n\x12\x43ontrolGateRequest\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x13\n\x0bgate_status\x18\x02 \x01(\t\"&\n\x13\x43ontrolGateResponse\x12\x0f\n\x07\x63ontrol\x18\x01 \x01(\t2P\n\x04Test\x12H\n\x0b\x43ontrolGate\x12\x18.test.ControlGateRequest\x1a\x19.test.ControlGateResponse\"\x00(\x01\x30\x01\x42$Z\"go-grpc-test/test-proto;test_protob\x06proto3'
)




_CONTROLGATEREQUEST = _descriptor.Descriptor(
  name='ControlGateRequest',
  full_name='test.ControlGateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial', full_name='test.ControlGateRequest.serial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gate_status', full_name='test.ControlGateRequest.gate_status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=77,
)


_CONTROLGATERESPONSE = _descriptor.Descriptor(
  name='ControlGateResponse',
  full_name='test.ControlGateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='control', full_name='test.ControlGateResponse.control', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['ControlGateRequest'] = _CONTROLGATEREQUEST
DESCRIPTOR.message_types_by_name['ControlGateResponse'] = _CONTROLGATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlGateRequest = _reflection.GeneratedProtocolMessageType('ControlGateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLGATEREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.ControlGateRequest)
  })
_sym_db.RegisterMessage(ControlGateRequest)

ControlGateResponse = _reflection.GeneratedProtocolMessageType('ControlGateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLGATERESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.ControlGateResponse)
  })
_sym_db.RegisterMessage(ControlGateResponse)


DESCRIPTOR._options = None

_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='test.Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='ControlGate',
    full_name='test.Test.ControlGate',
    index=0,
    containing_service=None,
    input_type=_CONTROLGATEREQUEST,
    output_type=_CONTROLGATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
