// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package test_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestClient interface {
	ControlGate(ctx context.Context, opts ...grpc.CallOption) (Test_ControlGateClient, error)
}

type testClient struct {
	cc grpc.ClientConnInterface
}

func NewTestClient(cc grpc.ClientConnInterface) TestClient {
	return &testClient{cc}
}

func (c *testClient) ControlGate(ctx context.Context, opts ...grpc.CallOption) (Test_ControlGateClient, error) {
	stream, err := c.cc.NewStream(ctx, &Test_ServiceDesc.Streams[0], "/test.Test/ControlGate", opts...)
	if err != nil {
		return nil, err
	}
	x := &testControlGateClient{stream}
	return x, nil
}

type Test_ControlGateClient interface {
	Send(*ControlGateRequest) error
	Recv() (*ControlGateResponse, error)
	grpc.ClientStream
}

type testControlGateClient struct {
	grpc.ClientStream
}

func (x *testControlGateClient) Send(m *ControlGateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testControlGateClient) Recv() (*ControlGateResponse, error) {
	m := new(ControlGateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServer is the server API for Test service.
// All implementations must embed UnimplementedTestServer
// for forward compatibility
type TestServer interface {
	ControlGate(Test_ControlGateServer) error
	mustEmbedUnimplementedTestServer()
}

// UnimplementedTestServer must be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (UnimplementedTestServer) ControlGate(Test_ControlGateServer) error {
	return status.Errorf(codes.Unimplemented, "method ControlGate not implemented")
}
func (UnimplementedTestServer) mustEmbedUnimplementedTestServer() {}

// UnsafeTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServer will
// result in compilation errors.
type UnsafeTestServer interface {
	mustEmbedUnimplementedTestServer()
}

func RegisterTestServer(s grpc.ServiceRegistrar, srv TestServer) {
	s.RegisterService(&Test_ServiceDesc, srv)
}

func _Test_ControlGate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServer).ControlGate(&testControlGateServer{stream})
}

type Test_ControlGateServer interface {
	Send(*ControlGateResponse) error
	Recv() (*ControlGateRequest, error)
	grpc.ServerStream
}

type testControlGateServer struct {
	grpc.ServerStream
}

func (x *testControlGateServer) Send(m *ControlGateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testControlGateServer) Recv() (*ControlGateRequest, error) {
	m := new(ControlGateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Test_ServiceDesc is the grpc.ServiceDesc for Test service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.Test",
	HandlerType: (*TestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlGate",
			Handler:       _Test_ControlGate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "test.proto",
}
